oro_menu_config:
    items:
        issues_tab:
            label: 'oro.issue.entity_plural_label'
            uri: '#'
            extras:
                position: 200

        issue_list:
            label: 'oro.issue.list_label'
            route: 'oro_issue_index'
            extras:
                position: 50
                routes: ['oro_issue_*']
        shortcut_issue_create:
            label: Create new issue
            route: oro_issue_create
            extras:
                description: Create new issue
        shortcut_issue_list:
            label: Show issues list
            route: oro_issue_index
            extras:
                description: List of issues

    tree:
        application_menu:
            children:
                issues_tab:
                    children:
                        issue_list: ~

        shortcuts:
            children:
                shortcut_issue_create: ~
                shortcut_issue_list: ~
oro_titles:
    oro_issue_index: Issues
    oro_issue_view: %%entity.title%%
    oro_issue_create: Create %%entityName%%
    oro_issue_update: %%entity.title%% - Edit
