oro_menu_config:
    items:
        issues_tab:
            label: 'oro.issue.menu.issues_tab.label'
            uri: '#'
            extras:
                position: 100
        issue_list:
            label: 'oro.issue.list_label'
            route: 'oro_issue_index'

    tree:
        application_menu:
            children:
                issue_list: ~