Oro\Bundle\IssueBundle\Entity\Issue:
    alias:                          oro_issue
    title_fields:                   [summary]
    route:
        name:                       oro_issue_view
        parameters:
            id:                     id
    search_template:                OroIssueBundle:Search:result.html.twig
    fields:
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
        -
            name:                   code
            target_type:            text
            target_fields:          [code]
        -
            name:                   type
            target_type:            text
            target_fields:          [type]
        -
            name:                   priority
            target_type:            text
            target_fields:          [priority]
        -
            name:                   resolution
            target_type:            text
            target_fields:          [resolution]
        -
            name:                   assignee
            relation_type:          many-to-one
            relation_fields:
                -
                    name: username
                    target_type: text
                    target_fields: [username,first_name,middle_name,email]
        -
            name:                   reporter
            relation_type:          many-to-one
            relation_fields:
                -
                    name: username
                    target_type: text
                    target_fields: [username,first_name,middle_name,email]
