parameters:
    oro_issue.entity.issue.class: Oro\Bundle\IssueBundle\Entity\Issue
    oro_issue.form.type.issue.class: Oro\Bundle\IssueBundle\Form\Type\IssueType
    oro_issue.form.handler.issue.class: Oro\Bundle\IssueBundle\Form\Handler\IssueHandler
    oro_issue.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    oro_issue.form.type.issue:
        class: %oro_issue.form.type.issue.class%
        tags:
            - { name: form.type, alias: oro_issue_form_issue }

    oro_issue.form.issue:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "oro_issue_form_issue"
            - "oro_issue_form_issue"

    oro_issue.form.handler.issue:
        class: %oro_issue.form.handler.issue.class%
        scope: request
        arguments:
            - @oro_issue.form.issue
            - @request
            - @doctrine.orm.entity_manager

    oro_issue.manager.api:
        class: %oro_issue.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_issue.entity.issue.class%
            - @doctrine.orm.entity_manager
